#!/usr/bin/env ruby

require "shellwords"
require "json"
require "optparse"

# This could be bundled in the PoC tooling.
# For now, in its own file for ease of use.
HANDLER_NIX = File.read("handler.nix")

module ToNixRefinements
  refine String do
    def to_nix()
      to_json()
    end
  end
  refine Integer do
    def to_nix()
      self
    end
  end
  refine TrueClass do
    def to_nix()
      "true"
    end
  end
  refine FalseClass do
    def to_nix()
      "false"
    end
  end
end
using ToNixRefinements

class CommandData
  private def initialize(data)
    @data = data
  end

  def self.from_path(path)
    cmd = [
      "nix-instantiate",
      "--eval",
      "--strict",
      "--json",
      "--expr",
      "#{HANDLER_NIX}",
      "--arg", "path", path,
    ]
    data = JSON.parse(`#{cmd.shelljoin()}`)
    self.new(data)
  end

  def parse!(nix_command, argv)
    args = []
    leftover = OptionParser.new() do |opts|
      opts.banner = [
        "Usage: nix <command> [...]", # TODO: summarize usage here?
        @data["shortDescription"],
        # Adds an empty line if description is set.
        @data["description"] && "",
        @data["description"],
        "CUSTOM OPTIONS\n\n",
      ].compact.join("\n")

      @passthrough = []

      command_options =
        case nix_command
        when "eval"
          # https://docs.lix.systems/manual/lix/stable/command-ref/new-cli/nix3-eval.html#options
          {
            "Nix eval options" => {
              "--apply=expr" => "Apply the function expr to each argument.",
              "--json" => "Produce output in JSON format, suitable for consumption by another program.",
              "--raw" => "Print strings without quotes or escaping.",
              "--read-only" => "Do not instantiate each evaluated derivation. This improves performance, but can cause errors when accessing store paths of derivations during evaluation.",
              "--write-to=path" => "Write a string or attrset of strings to path.",
            },
          }
        when "build"
          # https://docs.lix.systems/manual/lix/stable/command-ref/new-cli/nix3-build.html#options
          {
            "Nix build options" => {
              "--dry-run" => "Show what this command would do without doing it.",
              "--json" => "Produce output in JSON format, suitable for consumption by another program.",
              "--no-link" => "Do not create symlinks to the build results.",
              ["--out-link=path", "-o path"] => "Use path as prefix for the symlinks to the build results. It defaults to result.",
              "--print-out-paths" => "Print the resulting output paths",
              "--profile=path" => "The profile to operate on.",
              "--rebuild" => "Rebuild an already built package and compare the result to the existing store paths.",
              "--stdin" => "Read installables from the standard input. No default installable applied.",
            },
          }
        end

      prev_group_last = nil
      passthrough_options = {}.merge(command_options, {
        "Common evaluation options" => {
          # NOTE: two-args options not handled; when done within Nix, the Nix parser will handle those.
          # --arg name expr Pass the value expr as the argument name to Nix functions.
          # --argstr name string Pass the string string as the argument name to Nix functions.
          "--debugger" => "Start an interactive environment if evaluation fails.",
          "--eval-store=store-url" => "The URL of the Nix store to use for evaluation, i.e. to store derivations (.drv files) and inputs referenced by them.",
          "--impure" => "Allow access to mutable paths and repositories.",
          ["--include=path", "-I path"] => "Add path to the Nix search path. The Nix search path is initialized from the colon-separated NIX_PATH environment variable, and is used to look up the location of Nix expressions using paths enclosed in angle brackets (i.e., <nixpkgs>).",
          #--override-flake original-ref resolved-ref Override the flake registries, redirecting original-ref to resolved-ref.
        },
        # Skipping Common flake-related options
        "Logging-related options" => {
          "--debug" => "Set the logging verbosity level to 'debug'.",
          "--log-format=format" => "Set the format of log output; one of raw, internal-json, bar, bar-with-logs, multiline or multiline-with-logs.",
          ["--print-build-logs", "-L" ] => "Print full build logs on standard error.",
          "--quiet" => "Decrease the logging verbosity level.",
          ["--verbose", "-v"] => "Increase the logging verbosity level."
        },
        "Miscellaneous global options" => {
          # Handling this would break optparse's implicit handling :)
          #"--help" => "Show usage information.",
          "--offline" => "Disable substituters and consider all previously downloaded files up-to-date.",
          "--option" => "name value Set the Lix configuration setting name to value (overriding nix.conf).",
          "--refresh" => "Consider all previously downloaded files out-of-date.",
          "--repair" => "During evaluation, rewrite missing or corrupted files in the Nix store. During building, rebuild missing or corrupted store paths.",
          "--version" => "Show version information.",
        },
        "Options that change the interpretation of installables" => {
          ["--expr expr", "-E expr"] => "Interpret installables as attribute paths relative to the Nix expression expr.",
          ["--file file", "-f file"] => "Interpret installables as attribute paths relative to the Nix expression stored in file. If file is the character -, then a Nix expression will be read from standard input. Implies --impure.",
        },
      }).map do |group, options|
        options.map do |opt, desc|
          value = [opt, desc]
          if prev_group_last
            prev_group_last[1] += "\n\n  #{group}:\n"
            prev_group_last = nil
          end
          # Separate command-specific option from next set of options
          if opt == options.keys.last
            prev_group_last = value
          end
          value
        end
      end.flatten(1).to_h

      # Add this custom command options
      @data["options"].each do |name, config|
        desc = config["shortDescription"]
        if name == @data["options"].keys.last
          desc += "\n\nNIX OPTIONS\n\n  #{command_options.keys.first}:\n"
        end
        opts.on("--#{name}=#{config["type"]}", desc) do |value|
          args << "--arg"
          args << name
          # XXX validate and transform value from `type`!!
          args << value.to_nix
          # XXX collect `type = "list"` repeated args
        end
      end

      # Configure optparse to pass through the nix command options.
      passthrough_options.each do |parameter, description|
        opts.on(*parameter, "#{description}") do |v|
          @passthrough << parameter.split("=").first
          unless v == true
            @passthrough << v
          end
        end
      end
    end
      .parse!(argv)
    args + leftover
  end

  def nix!(command, *argv)
    cmd = [
      "nix",
      "--extra-experimental-features", "nix-command",
      command,
      "-f", "./default.nix",
      *argv,
    ]
    #$stderr.puts " $ #{cmd.shelljoin}"
    exec(*cmd)
  end

  def build!(argv)
    nix!("build", *parse!("build", argv))
  end

  def eval!(argv)
    nix!("eval", *parse!("eval", argv))
  end
end

COMMAND_BUILD = "command-build.nix"

$command = ARGV.shift
unless [
    "build",
    "eval",
].include?($command)
  $stderr.puts "!!! This wrapper only allows `./nix build` and `./nix eval` to be LARP'd"
  exit 1
end

unless File.exist?(COMMAND_BUILD)
  $stderr.puts "warning: no #{COMMAND_BUILD.inspect} to work with..."
  $stderr.puts "         ... calling conventional nix #{$command}."
  exec("nix", $command, *ARGV)
end

command = CommandData.from_path("./command-build.nix")
pp command.send("#{$command}!".to_sym ,ARGV.dup)
